# Generated by Django 5.1.1 on 2024-09-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0003_rename_title_slider_title1_slider_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
