# Generated by Django 5.1.1 on 2024-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0004_alter_slider_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=300),
        ),
    ]
