# Generated by Django 5.1.1 on 2024-10-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0005_alter_footer_description_alter_slider_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
