# Generated by Django 5.1.1 on 2024-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0007_alter_aboutus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.CharField(max_length=650),
        ),
    ]
