# Generated by Django 5.1.1 on 2024-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0008_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=650)),
            ],
        ),
    ]
