# Generated by Django 5.1.1 on 2024-10-01 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0009_indexparagraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexparagraph',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='indexparagraph',
            name='content2',
            field=models.CharField(default=django.utils.timezone.now, max_length=650),
            preserve_default=False,
        ),
    ]
