# Generated by Django 5.1.1 on 2024-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0010_rename_content_indexparagraph_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(default=list)),
                ('product_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=10)),
            ],
        ),
    ]
