# Generated by Django 5.1.1 on 2024-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AK', '0015_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_specs',
            field=models.CharField(default='link_pdf_placeholder', max_length=150),
        ),
    ]
